const mongoose=require('mongoose')

const eventSchema=new mongoose.Schema({
    pictures:[String],
    title:{
        type:String,
        required:true,
    },
    information:{
        type:String,
        maxlength:500,
    },
    startTime:{
        type:Date,
        required:true,
    },
    endTime:{
        type:Date,
        required:true,
    },
    host:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true,
    },
    city:{
        type:String,
        required:true,
    },
    guests:{
        type:Number,
        default:0
    },
    averageAge:{
        type:Number,
        default:0,
    },
    genderRatio:{
        male:{
            type:Number,
            default:0,
        },
        female:{
            type:Number,
            default:0,
        }
    },
    attendRequests:[
        {
        user:{
           type:mongoose.Schema.Types.ObjectId,
           ref:'User'
        },
        males:{
            type:Number,
            required:true
        },
        females:{
            type:Number,
            required:true
        },
        ages:[Number],
        images:[String],
        status:{
            type:String,
            enum:["Pending","Accepted","Rejected"],
            default:"Pending"
        },
    }
    ],
    messages:[
        {
            sender:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'User',
            },
            content:{type:String},
            timestamp:{
                type:Date,
                default:Date.now
            }
        }
    ],
    directions:{
        type:String,
        default:null
    }
},{timestamps:true})

const Event=mongoose.model('Event',eventSchema)

module.exports=Event